### ISSUE TITLE
expanded Storage

### ISSUE THREAD

**Issue by Noahfrechette** [NinjaPhenix/container-library#10]
The Expanded storage wont notice the newest version of this mod and is crashing me

**Comment by NinjaPhenix** [comment]
Any crash logs, or even more information like specific versions of the mod your using, mod loader, minecraft version, ect. Can''t help without more information.

**Comment by NinjaPhenix** [comment]
Going to close this as I lack any information needed to help, I can only assume you have downloaded the fabric version instead of forge version by mistake.
