### ISSUE TITLE
Expanded Storage Crash with Current Version of Ninjaphenix Unmet Dependency Error

### ISSUE THREAD

**Issue by PuppetMasterZee** [NinjaPhenix/container-library#11]
MC 1.18
Fabric Loader 0.12.9
Fabric API 0.44.0.18
Expanded Storage: 7.3.3+1.1.18
Library: ninjaphenix-container-library-1.2.7+1.18

Note: These are the only mods included (for diagnostic purposes)
Yes, I know this is on issue #10 but I saw the initial report hadn't provided the additional information requested.

Crash Report Link Attached as image
https://imgur.com/a/No2uSpI

**Comment by NinjaPhenix** [comment]
1.2.7 is for forge, use this one: https://www.curseforge.com/minecraft/mc-mods/ninjaphenixs-container-library/files/3549144

**Comment by PuppetMasterZee** [comment]
> 1.2.7+1.18 is for forge, use this one: https://www.curseforge.com/minecraft/mc-mods/ninjaphenixs-container-library/files/3549144

Ah, thanks.  Sorry about that.  More tired than I thought.

**Comment by NinjaPhenix** [comment]
That's fine.
