### ISSUE TITLE
Mod Failed to Load Correctly 1.18.1 forge-39.0.9

### ISSUE THREAD

**Issue by Camawama** [NinjaPhenix/container-library#13]
![errormc](https://user-images.githubusercontent.com/43620900/147882689-5b39aab6-7294-4a12-bb35-ea06317ea54e.png)
[latest.log](https://github.com/NinjaPhenix/container-library/files/7799450/latest.log)

**Comment by NinjaPhenix** [comment]
Thanks for reporting, will try and get a new build out wthin a few hours.

**Comment by NinjaPhenix** [comment]
Should be fixed.
https://www.curseforge.com/minecraft/mc-mods/ninjaphenixs-container-library/files/3591316
https://modrinth.com/mod/ninjaphenix-container-library/version/XoWz3PCG
