### ISSUE TITLE
[BUG] Keybind doesn't register

### ISSUE THREAD

**Issue by Zwikkry** [NinjaPhenix/container-library#2]
Minecraft ver: 1.17.1
Fabric API ver: 0.40.1
NinjaPhenix's Container Library ver: 1.0.2

The mod being used in this example is Expanded Storage. When you press the default key "g", the UI to change the chest interface doesn't pop up. Even when changing the default keybind, it doesn't register. I've restarted the game to exclude that being an issue.

Mods used:
expandedstorage-7.2.2+1.17.1.jar
ninjaphenix-container-library-1.0.2+1.17.1.jar

[latest.log](https://github.com/NinjaPhenix/container-library/files/7239238/latest.log)

**Comment by NinjaPhenix** [comment]
If you don't have amecs api installed then you also need to hold shift, if this works then I'll make it more obvious on the curseforge page.

**Comment by Zwikkry** [comment]
I've tried the old option (shift + W) and tried the new one with and without shift (G & shift + G), both give 0 results. And I had no idea that Amecs was necesarry for this to work, so my bad for that. I'll see if it works with amecs installed

**Comment by NinjaPhenix** [comment]
Amecs is only required to configure the modifier key, will do a bit of testing myself outside of dev environment.

**Comment by Zwikkry** [comment]
Seems to be working now, I'm using the newest Expanded Storage 7.2.3 and the Container Library you posted here (in combination with amecs API). Without amecs API it defaults to Shift + G, so that seems to be in working order as well.

**Comment by NinjaPhenix** [comment]
Sweet will post a new build of NCL publicly in a bit.

**Comment by NinjaPhenix** [comment]
Build is public:
CF: <https://www.curseforge.com/minecraft/mc-mods/ninjaphenixs-container-library/files/3475724>
MR: <https://modrinth.com/mod/ninjaphenix-container-library/version/eD4QmN4U>
