### ISSUE TITLE
Changing GUI isn't applying the new GUI 

### ISSUE THREAD

**Issue by Zwikkry** [NinjaPhenix/container-library#5]
Minecraft ver: 1.17.1
Fabric API ver: 0.40.1
NinjaPhenix's Container Library ver: 1.0.2

When you try swapping the GUI for chests or whatever container uses this library, it won't change to the new GUI once applied (using default keybinds SHIFT + G). I've tested this with just the 3 mods required for Expanded Storage (the container mod I'm using to replicate this).

Mods used:
amecs-1.3.4+mc.1.17.jar
expandedstorage-7.2.4+1.17.1.jar
ninjaphenix-container-library-1.2.0+1.17.1.jar

[latest.log](https://github.com/NinjaPhenix/container-library/files/7271925/latest.log)

**Comment by NinjaPhenix** [comment]
Can't replicate this, if the GUI displays fully on one screen e.g. doesn't need scrolling or pages then this is intentional.
Otherwise can you give me the scaled window size ( visible in F3 screen on right ) for minecraft and inventory size.

**Comment by Zwikkry** [comment]
Seems I missed that part, it's definitely working as intended then. Just tested it by changing my GUI scale to 4 instead of 3 and I can change it. This issue can be closed.
