### ISSUE TITLE
Taking an item from a chest will immediately drop the item from your inventory

### ISSUE THREAD

**Issue by Zwikkry** [NinjaPhenix/container-library#6]
Minecraft ver: 1.17.1
Fabric API ver: 0.40.1
NinjaPhenix's Container Library ver: 1.0.2

When trying to take an item from a single or double chest, the item will be immediately expelled from inventory onto the ground. I've tried changing the GUI to exclude it being the interface type, but since I can't change it (see #5) I can't test it without changing it in the config file itself (and I don't know what variables are used for the interface types, so pretty hard to replicate it with other GUI types)

Mods used:
amecs-1.3.4+mc.1.17.jar
expandedstorage-7.2.4+1.17.1.jar
ninjaphenix-container-library-1.2.0+1.17.1.jar

**Comment by NinjaPhenix** [comment]
Cannot seem to replicate the issue where items are immediately dropped again however there is an issue with checking if the cursor is in bounds so hopefully fixing that fixes this.

**Comment by NinjaPhenix** [comment]
Can you see if this fixes it [ninjaphenix-container-library-1.2.1+1.17.1.jar](https://cdn.discordapp.com/attachments/577531478116925470/893934898732208209/ninjaphenix-container-library-1.2.11.17.1.jar)

**Comment by Zwikkry** [comment]
This seems to be fixed now. Taking items from a chest works as intended with the new version.

**Comment by NinjaPhenix** [comment]
Great, will release the new build now.

**Comment by NinjaPhenix** [comment]
Just released the update.
Thanks for all the help with testing and reporting bugs.

CF: https://www.curseforge.com/minecraft/mc-mods/ninjaphenixs-container-library/files/3479348
MR: https://modrinth.com/mod/ninjaphenix-container-library/version/TKtV2Aio
